# Generated by Django 4.1 on 2024-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEquipe', models.CharField(max_length=5)),
                ('Nome_Encaregado', models.CharField(max_length=100)),
                ('Matricula_Encaregado', models.CharField(max_length=100)),
                ('Nome_Eletricista_1', models.CharField(max_length=100)),
                ('Matricula_Eletricista1', models.CharField(max_length=8)),
                ('Nome_Eletricista_2', models.CharField(max_length=100)),
                ('Matricula_Eletricista2', models.CharField(max_length=8)),
                ('Nome_Eletricista_3', models.CharField(max_length=100)),
                ('Matricula_Eletricista3', models.CharField(max_length=8)),
                ('Nome_Eletricista_4', models.CharField(max_length=100)),
                ('Matricula_Eletricista4', models.CharField(max_length=8)),
                ('Nome_Ajudante_1', models.CharField(max_length=100)),
                ('Matricula_Ajudante1', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projeto', models.CharField(max_length=12)),
                ('Nota', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=20)),
                ('Descricao', models.CharField(max_length=50)),
                ('Local', models.CharField(max_length=50)),
                ('Data_Inicio', models.DateField(blank=True, null=True)),
                ('Data_Fim', models.DateField(blank=True, null=True)),
                ('Data_Programacao', models.DateField(blank=True, null=True)),
                ('Equipe', models.CharField(max_length=5)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
