# Generated by Django 5.0.6 on 2024-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meuprojeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='Status',
            field=models.CharField(choices=[('Em Programacao', 'Em programacao'), ('Programado', 'Programado'), ('Em execucao', 'Em execucao'), ('Executado', 'Executado'), ('Executado Fora Prazo', 'Executado Fora Prazo'), ('Nao Executado', 'Nao Executado'), ('Interropida', 'Interropida'), ('Medicao', 'Medicao'), ('Entregue', 'Entregue'), ('Pago', 'Pago')], max_length=30),
        ),
    ]
