# Generated by Django 5.0.6 on 2024-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meuprojeto', '0002_alter_servico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='evidencia_execucao',
            field=models.ImageField(blank=True, null=True, upload_to='emp_profile_pics/'),
        ),
    ]
