# Generated by Django 5.0.6 on 2024-07-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meuprojeto', '0004_alter_servico_equipe_alter_servico_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='Equipe',
            field=models.CharField(max_length=5),
        ),
    ]
