# Generated by Django 5.0.6 on 2024-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meuprojeto', '0007_servico_mes_servico_servico_ano_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='Mes_servico',
            field=models.CharField(choices=[('Jan', 'Janeiro'), ('Fev', 'Fevereiro'), ('Mar', 'Março'), ('Abr', 'Abril'), ('Mai', 'Maio'), ('Jun', 'Junho'), ('Julho', 'Julho'), ('Ago', 'Agosto'), ('Set', 'Setembro'), ('Out', 'Outubro'), ('Nov', 'Novembro'), ('Dez', 'Desembro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servico',
            name='ano_servico',
            field=models.CharField(max_length=4),
        ),
    ]
